### ISSUE TITLE
Request for Publishing Rights

### ISSUE THREAD

**Issue by TheCuteFoxxy** [emillly-b/Azrael.Net#2]
Hello,

We (Azrael Interactive LLC) would like to request full rights to the package in order to publish it on NuGet. You would retain all available copyrights (Excluding our trademarks and copyrights to the API itself) and would retain access to manage the package via Github.

Please let me know.

Kind regards,

Justyn Freeman
Chief Executive Officer
Azrael Interactive LLC

**Comment by emillly-b** [comment]
Completely fine with that. What do you need from me?

**Comment by TheCuteFoxxy** [comment]
Just your github email so I can give you access to our repo, and archive/deletion of this repo so our repo is the only one retained.

**Comment by TheCuteFoxxy** [comment]
The github email you can send me via Discord rather than Github so its not public.
